
- name: provision VM on GCP
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    service_account_file: tvb-cluster-phare-1f9becec5035.json
    auth_kind: serviceaccount
    project: tvb-cluster-phare
    zone: "europe-north1-a"
    region: "europe-north1"
  tasks:
    - name: create a disk
      gcp_compute_disk:
        name: "phare-disk"
        size_gb: 15
        source_image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts"
        zone: "{{ zone }}"
        auth_kind: "{{ auth_kind }}"
        project: "{{ project }}"
        service_account_file: "{{ service_account_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: disk

    - name: create a network
      gcp_compute_network:
        name: "phare-network"
        project: "{{ project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ service_account_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: network

# vim: ts=2:sts=2:sw=2:expandtab:ai:list
