
- name: provision VM on GCP
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    auto_delete_vm_disk: false
    recreate_disk: false
    recreate_instance: false

  tasks:

    - name: remove instance
      gcp_compute_instance:
        name: "phare-vm"
        state: absent
      when: recreate_disk or recreate_instance

    - name: remove disk
      gcp_compute_disk:
        name: "phare-disk"
        state: absent
      when: recreate_disk

    - name: create a disk
      gcp_compute_disk:
        name: "phare-disk"
        size_gb: 15
        source_image: "projects/gce-uefi-images/global/images/family/centos-7"
        state: present
      register: disk

    - name: create a network
      gcp_compute_network:
        name: "phare-network"
        state: present
      register: network

    - name: show network register
      debug:
        var: network

    - name: allow SSH through firewall
      gcp_compute_firewall:
        name: "phare-ssh-allow"
        network: "global/networks/{{ network.name }}"
        allowed:
          - ip_protocol: tcp
            ports:
              - '22'
        state: present        

    - name: create an IP address
      gcp_compute_address:
        name: "phare-ip"
        state: present
      register: address

    - name: create instance
      gcp_compute_instance:
        name: "phare-vm"
        machine_type: "f1-micro"
        disks:
          - auto_delete: "{{ auto_delete_vm_disk }}"
            boot: true
            source: "{{ disk }}"
        network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: 'External NAT'
                nat_ip: "{{ address }}"
                type: 'ONE_TO_ONE_NAT'
      register: instance

    - name: Wait SSH to come up
      wait_for: host={{ address.address }} port=22 delay=10 timeout=60

    - name: Add host to groupname
      add_host:
        name: phare
        groupname: phares
        hostname: "{{ address.address }}"
        ansible_hostname: "{{ address.address }}"


- name: Configure new instances
  hosts: phares
  connection: ssh
  become_method: sudo
  tasks:
    - name: Set hostname
      hostname:
        name: phare.tvb-ins.fr
